# Generated by Django 3.0.8 on 2020-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201101_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='familygroup',
        ),
        migrations.AddField(
            model_name='profile',
            name='family_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FamilyGroup',
        ),
    ]
