# Generated by Django 3.0.8 on 2020-11-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201105_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
            preserve_default=False,
        ),
    ]
