# Generated by Django 3.0.8 on 2020-11-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201115_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
