# Generated by Django 3.0.8 on 2020-12-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201115_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='disease_type',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='required_doses',
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.CharField(blank=True, choices=[('Canine parainfluenza virus', 'Canine parainfluenza virus'), ('Canine Bordetella bronchiseptica', 'Canine Bordetella bronchiseptica'), ('Canine Leptospira', 'Canine Leptospira'), ('Canine Borrelia', 'Canine Borrelia'), ('Canine enteric coronavirus', 'Canine enteric coronavirus'), ('Canine distemper virus', 'Canine distemper virus'), ('Canine adenovirus', 'Canine adenovirus'), ('Canine parvovirus type 2', 'Canine parvovirus type 2'), ('Canine Rabies virus', 'Canine Rabies virus'), ('Feline parvovirus', 'Feline parvovirus'), ('Feline leukaemia virus', 'Feline leukaemia virus'), ('Feline infectious peritonitis', 'Feline infectious peritonitis'), ('Feline herpesvirus type 1', 'Feline herpesvirus type 1'), ('Feline Chlamydia felis', 'Feline Chlamydia felis'), ('Feline calicivirus', 'Feline calicivirus'), ('Feline Bordetella', 'Feline Bordetella'), ('Feline Rabies virus', 'Feline Rabies virus'), ('Feline immunodeficiency virus', 'Feline immunodeficiency virus')], max_length=200),
        ),
    ]
